// AUTO-GENERATED by scripts/gen-blur.mjs — do not edit by hand.
// Map of public image path -> base64 blur placeholder for next/image.
export const blurData: Record<string, string> = {
  "/images/gbp/photo-1.jpg": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoMABAAA4BaJQBOgBpAwBKuoBgAAM4zEF41JbvgU4ozXhhA/eM8q0Poiorl2qWbMkwOaSjMbXNnadZ6ZnelWnBJG8+bp/JiMAAAAA==",
  "/images/gbp/photo-2.jpg": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoMABAAA4BaJQBdgB6UXb/E9mEAAP7EWRU6prfvepBzyAU4yJ7KZgkhXMO19Su9KczcWt6M1xwRAeB1bGMW1Txcha/0YfEWiHg7wXTl2XCBAAAA",
  "/images/gbp/photo-3.jpg": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAAwAA4BaJYwCdAYtzbWxgSEwAP6J8Mh1r1uveoHUXARzt6+owGUVX985ezY0sWYDQYh7Ti8KguMUNKDZj2pJWroocUA5j0AAAA==",
  "/images/gbp/photo-5.jpg": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAwAA4BaJYgCdADdSk57MwBVAAD+o2lsM+Yssh8xKI+h3PgwAfN74IFAkzcGbnz7BE+YM6CTEkowQy/KGMr9hEHPLW47600YW+IA",
  "/images/gbp/photo-6.jpg": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAQCdASoQAAwAA4BaJZQAAfnzAAD+5sAh6b3hfnbmYSDitp51ZSzVS1M0YsSDkhFpaIxwppvXGMvY7uXAJ93QoAA=",
  "/images/gbp/photo-7.jpg": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwAA4BaJQBOgBo+4Hp8jwAA/uqW6kQ+u+PB+7XTg/TcoOHyPPWzrIxEOTYMeGVy99pjsUmtRNPNvOCueZjeop931e8KZBZkKBJJAAA=",
  "/images/gbp/photo-8.jpg": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwAA4BaJYwCdAC4i6itjAAAy07+38c6iqT5cmZkP45ow0dVxUwWHRYclSoN6AfhZQ7ADwvPH9p8zXfqMfh773SkQAAA",
  "/images/services/asphalt-patching-sealing.jpg": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoMABAAA4BaJbACdADynkFpAADMb7gyjogat/BP8h5XmoRRMUAXoWkZlqUdFVJJQDgM5vT30wq/H9BTrIsBtFnjGIRfQm/EJ7ygQAAA",
  "/images/services/concrete-sealing.jpg": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMABAAA4BaJYwCdAEOlgpQbgAA/uej1qJh39VisTGBaiucNvpAPWveIV1NsZvBKwKjihZcwEMs19iGH7jBP4+JEEpAxrQDYwAAAA==",
  "/images/services/crack-after.jpg": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoMABAAA4BaJZwAAqrjqEwgAPk+y9kIdq681VKfdIIMKgIA",
  "/images/services/crack-before.jpg": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoMABAAA4BaJZwAAl08ZGuAAPzXYHyIOBm7rkz0i1rDbchlYoLCgiz3l+PQoQAA",
  "/images/services/paver-sanding-sealing.jpg": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAwAA4BaJYgCdAEfA1Mn2oAA/kD6PVSePcXsT0P5wWT2sELWVNWKVgUBVgCQc5NmthdXBpLGqtcXZhhq2m0ttCW8feGGHwAAAA=="
};
