// Generates lib/blurData.generated.ts — a map of public image path -> a tiny
// base64 blur placeholder, used by next/image's placeholder="blur" for the
// local (non-Sanity) images. Sanity images get their blur (lqip) from the GROQ
// query instead. Re-run after swapping any image in public/images:
//   node scripts/gen-blur.mjs
import sharp from "sharp";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const DIRS = ["public/images/gbp", "public/images/services"];
const map = {};

async function blur(file) {
  const buf = await readFile(file);
  const out = await sharp(buf)
    .resize(16, 16, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();
  return `data:image/webp;base64,${out.toString("base64")}`;
}

for (const dir of DIRS) {
  const files = (await readdir(dir)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f));
  for (const f of files) {
    const file = path.join(dir, f);
    // Key by the public path exactly as referenced in components: leading slash,
    // forward slashes, no "public" prefix (e.g. "/images/gbp/photo-1.jpg").
    const key = "/" + path.relative("public", file).replace(/\\/g, "/");
    map[key] = await blur(file);
  }
}

const body =
  "// AUTO-GENERATED by scripts/gen-blur.mjs — do not edit by hand.\n" +
  "// Map of public image path -> base64 blur placeholder for next/image.\n" +
  "export const blurData: Record<string, string> = " +
  JSON.stringify(map, null, 2) +
  ";\n";

await writeFile("lib/blurData.generated.ts", body);
console.log(`wrote lib/blurData.generated.ts (${Object.keys(map).length} entries)`);
